services:
  server:
    build:
      context: ../src/backend
      dockerfile: ../../docker/Dockerfile-back
    restart: on-failure
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
    env_file:
      - ../.env
    depends_on:
      - db
    networks:
      - internal
    expose:
      - 3000
  db:
    image: postgres:17.5-alpine
    env_file:
      - ../.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached
    networks:
      - internal

  caddy:
    image: caddy:2.10.0-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - internal
    depends_on:
      - server

volumes:
  postgres-data:

networks:
  internal:
    driver: bridge
