services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: filmdb
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - film-network

  backend:
    build:
      context: ../src/backend
      dockerfile: ../../docker/backend/Dockerfile
    container_name: backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: filmdb
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      OMDB_API_KEY: ${OMDB_API_KEY}
    volumes:
      - ./backend/entrypoint.sh:/entrypoint.sh
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - film-network

  proxy:
    image: caddy:alpine
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend
    networks:
      - film-network

networks:
  film-network:

volumes:
  mysql-data:
