CREATE DATABASE IF NOT EXISTS filmdb;
USE filmdb;

CREATE TABLE IF NOT EXISTS films (
    tconst VARCHAR(20) PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ratings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tconst VARCHAR(20),
    rating TINYINT UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tconst) REFERENCES films(tconst)
) ENGINE=InnoDB;
